# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170825_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Add_Picture',
        ),
    ]
