# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advise', models.CharField(default='Enter Your Advise Topic', max_length=50)),
                ('Quote', models.CharField(default='Enter Your Quote', max_length=50)),
                ('Explanation', models.TextField(default='Explain your advise')),
                ('Created_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
