# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
